version: "3.9"
services:
  ai-cat-api:
    build: .
    ports:
      - "5002:5000"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      BASIC_AUTH_USERNAME: ${BASIC_AUTH_USERNAME}
      BASIC_AUTH_PASSWORD: ${BASIC_AUTH_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PLANET_SCALE_SERVICE_TOKEN_ID: ${PLANET_SCALE_SERVICE_TOKEN_ID}
      PLANET_SCALE_SERVICE_TOKEN_SECRET: ${PLANET_SCALE_SERVICE_TOKEN_SECRET}
      PLANET_SCALE_ORG: ${PLANET_SCALE_ORG}
      PLANET_SCALE_TEST_DB_NAME: ${PLANET_SCALE_TEST_DB_NAME}
      PLANET_SCALE_TEST_DB_BRANCH: ${PLANET_SCALE_TEST_DB_BRANCH}
    depends_on:
      - ai-cat-api-mysql
    volumes:
      - ./.flake8:/.flake8
      - ./Makefile:/Makefile
      - ./pyproject.toml:/pyproject.toml
      - ./poetry.lock:/poetry.lock
      - ./src:/src
      - ./tests:/tests
    command: uvicorn main:app --reload --host 0.0.0.0 --port 5000
  ai-cat-api-mysql:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: ai_cat_api_test
      MYSQL_USER: ai_cat_api_test
      MYSQL_PASSWORD: dbPassword(888
      MYSQL_ROOT_PASSWORD: dbRootPassword(888
      TZ: UTC
    ports:
      - "33060:3306"
    volumes:
      - ai-cat-api-test-data-store:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d
volumes:
  ai-cat-api-test-data-store:
