[tool.black]
exclude = '.venv'

[tool.poetry]
name = "ai-cat-api"
version = "0.1.0"
description = ""
authors = ["keitakn <keita.koga.work@gmail.com>"]
readme = "README.md"
packages = [{include = "ai_cat_api"}]

[tool.poetry.dependencies]
python = "^3.11"
uvicorn = "0.29.0"
fastapi = "0.110.0"
openai = "1.14.2"
flake8 = "^7.0.0"
black = "24.3.0"
tiktoken = "0.6.0"
asyncio = "^3.4.3"
aiomysql = "^0.2.0"
pytest = "8.1.1"
pytest-asyncio = "0.23.6"
mypy = "1.9.0"
asyncstdlib = "3.12.2"
pytest-env = "^1.1.1"
pytest-xdist = "^3.5.0"
httpx = "0.27.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
env = [
    "IS_TESTING=1",
]
addopts = "-n auto"

[tool.mypy]
files = "src/"
python_version = "3.11"
ignore_missing_imports = true
