[tool.black]
exclude = '.venv'

[tool.poetry]
name = "ai-cat-api"
version = "0.1.0"
description = ""
authors = ["keitakn <keita.koga.work@gmail.com>"]
readme = "README.md"
packages = [{include = "ai_cat_api"}]

[tool.poetry.dependencies]
python = "^3.11"
uvicorn = "^0.23.2"
fastapi = "^0.101.0"
openai = "^0.27.6"
flake8 = "^6.0.0"
black = "^23.3.0"
tiktoken = "^0.4.0"
asyncio = "^3.4.3"
aiomysql = "^0.2.0"
pytest = "^7.4.1"
pytest-asyncio = "^0.21.1"
mypy = "^1.5.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
