[tool.black]
exclude = '.venv'

[tool.poetry]
name = "ai-cat-api"
version = "0.1.0"
description = ""
authors = ["keitakn <keita.koga.work@gmail.com>"]
readme = "README.md"
packages = [{include = "ai_cat_api"}]

[tool.poetry.dependencies]
python = "^3.11"
uvicorn = "^0.27.0"
fastapi = "^0.109.0"
openai = "^1.10.0"
flake8 = "^7.0.0"
black = "^24.1.0"
tiktoken = "^0.5.2"
asyncio = "^3.4.3"
aiomysql = "^0.2.0"
pytest = "^7.4.4"
pytest-asyncio = "^0.23.3"
mypy = "^1.8.0"
asyncstdlib = "^3.12.0"
pytest-env = "^1.1.1"
pytest-xdist = "^3.5.0"
httpx = "^0.26.0"
pydantic = "^2.5.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
env = [
    "IS_TESTING=1",
]
addopts = "-n auto"

[tool.mypy]
files = "src/"
python_version = "3.11"
ignore_missing_imports = true
